function [value,isterminal,direction] = event_LO(t,in2)
%event_LO
%    [VALUE,ISTERMINAL,DIRECTION] = event_LO(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    22-Dec-2022 09:37:02

x1 = in2(1,:);
value = x1-1.0./2.0;
if nargout > 1
    isterminal = 1.0;
end
if nargout > 2
    direction = 1.0;
end
