function out1 = func_M(t,in2)
%func_M
%    OUT1 = func_M(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    22-Dec-2022 09:37:02

x1 = in2(1,:);
out1 = reshape([1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,x1.^2.*6.0],[4,4]);
