function out1 = func_f_disp(t,in2)
%FUNC_F_DISP
%    OUT1 = FUNC_F_DISP(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    22-Dec-2022 09:37:02

x1 = in2(1,:);
x2 = in2(2,:);
x3 = in2(3,:);
x4 = in2(4,:);
out1 = [x3;x4;x1.*-1.8e+3-sin(x2).*5.886e+1+x1.*x4.^2.*6.0+9.0e+2;x1.*(cos(x2).*9.81e+2+x3.*x4.*2.0e+2).*(-3.0./5.0e+1)];
